---
title: Sus & Eco
baseURL: "/"
params:
  palette: yellow
  header:
    type: header
    template: header
    title: Sus & Eco
    tagline: A friendly chat about sustainable development, innovation & personal
      development
    logo_img: "/images/sus-eco-fontwork-sans-400-copy.png"
    logo_img_alt: Sus&Eco
    background_img: "/images/annie-spratt-tkvocukoecy-unsplash.jpg"
    has_nav: true
    nav_links:
    - type: action
      template: action
      label: Home
      url: "/"
      style: link
      icon_class: ''
      new_window: false
      no_follow: false
    - type: action
      template: action
      label: About
      url: "/about"
      style: link
      icon_class: ''
      new_window: false
      no_follow: false
    - type: action
      template: action
      label: Style Guide
      url: "/style-guide"
      style: link
      icon_class: ''
      new_window: false
      no_follow: false
    - type: action
      template: action
      label: Contact
      url: "/contact"
      style: link
      icon_class: ''
      new_window: false
      no_follow: false
    has_social: true
    social_links:
    - type: action
      template: action
      label: Twitter
      url: https://twitter.com/
      style: icon
      icon_class: twitter
      new_window: true
      no_follow: false
    - type: action
      template: action
      label: Instagram
      url: https://www.instagram.com/
      style: icon
      icon_class: instagram
      new_window: true
      no_follow: false
    - type: action
      template: action
      label: GitHub
      url: https://github.com/
      style: icon
      icon_class: github
      new_window: true
      no_follow: false
    - type: action
      template: action
      label: LinkedIn
      url: https://www.linkedin.com/
      style: icon
      icon_class: linkedin
      new_window: true
      no_follow: false
    - type: action
      template: action
      label: DEV
      url: https://dev.to/
      style: icon
      icon_class: dev
      new_window: true
      no_follow: false
  footer:
    type: footer
    template: footer
    content: '&copy; Stackbit. All rights reserved. This Jamstack site was created
      with <a href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank"
      rel="noopener">Stackbit</a>. Create yours <a href="https://app.stackbit.com/create?theme=fjord&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>'
    links: []
  domain: https://parallel-chestnut-c2241.netlify.app
  favicon: "/images/s-efavicon.png"
taxonomies:
  stub: stub
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
